CREATE TABLE medicos (

  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  dni VARCHAR(15) NOT NULL UNIQUE,
  especialidad VARCHAR(100) NOT NULL,
  calle VARCHAR(100) NOT NULL,
  distrito VARCHAR(100) NOT NULL,
  numero VARCHAR(15) NULL,
  ciudad VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)

);